### ISSUE TITLE
Publishing to Obsidian plugins?

### ISSUE THREAD

**Issue by rlmcneary2** [NicoNekoru/obsidan-advanced-table-xt#4]
Sorry to open an issue to ask a question but I don't see another way to do that.

I installed the plugin manually because I couldn't find it on Obsidian's plugins page. Did I miss it? I searched for "Sheets Extended" but it wasn't listed.

Also is this a real code block? Where does `sheets` come from?

<pre>
```sheets
  TODO
```
</pre>

**Comment by NicoNekoru** [comment]
The plugin is not available on Obsidian's plugins [yet](https://github.com/obsidianmd/obsidian-releases/pull/2281).

Yes that code block is real although the language should be `sheet` for using this plugin and your syntax for the body is wrong since it should be a markdown table. This is [standard markdown syntax](https://help.obsidian.md/Editing+and+formatting/Basic+formatting+syntax#Code+blocks) and the plugin is the same as many others in it's implementation.

````
```sheet
| foo | bar |
| --- | --- |
| 123 | 456 |
```
````
<img width="86" alt="image" src="https://github.com/NicoNekoru/obsidan-advanced-table-xt/assets/66227158/7ebde7d4-848d-4538-b069-b7ec3bacf83c">

For more examples see the [readme](https://github.com/NicoNekoru/obsidan-advanced-table-xt#readme)
