### ISSUE TITLE
Issue with math

### ISSUE THREAD

**Issue by ndharari** [NicoNekoru/obsidan-advanced-table-xt#7]
When using math in a table, the inline math does not get rendered.

**Comment by abiriadev** [comment]
I have the same problem.

**Comment by Ce1este** [comment]
I'm having this problem too.

I've found that **inline math** fail to render (or only partially) when using markdown's native tables, while they render fine when using the `sheet` code block.

![image](https://github.com/NicoNekoru/obsidan-advanced-table-xt/assets/51806751/54200e1c-3f56-4197-ab8f-b627eca89d2d)

---

And I sometimes use the `<br>` syntax to make the text within a table line breaks, and this will not work when using the `sheet` code block.

I'm curious if there's a better way to accomplish this?

**Comment by abiriadev** [comment]
![image](https://github.com/NicoNekoru/obsidan-advanced-table-xt/assets/72962900/b3ba75f3-e89b-4217-af76-09ab8a486894)
![image](https://github.com/NicoNekoru/obsidan-advanced-table-xt/assets/72962900/c7c8802a-4aaa-4c2d-b106-6ac6b8e64973)

> It will handle inline TeX properly.

I guess I was wrong. It renders correctly on the initial load (e.g. 'Reload app without saving'), but not immediately after subsequent renders (by editing, or opening in a new tab, etc.).

![image](https://github.com/NicoNekoru/obsidan-advanced-table-xt/assets/72962900/5c357de3-2e72-4236-8f08-08a282df1e1c)

This seems to be because the TeX is converted into a MathJax element after the first render.

**Comment by abiriadev** [comment]
I made a pull request for this: #9
